// css
import "react-toastify/dist/ReactToastify.css";
import "@/styles/globals.scss";

// components
import GlobalProvider from "@/components/GlobalProvider";

export const metadata = {
  title: "Gain B2C",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
